AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 Bucket with IAM Role for Lambda

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create

  LambdaExecutionRoleName:
    Type: String
    Description: Name of the IAM Role Lambda can assume

Resources:

  SecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: b8babe04-f522-4f09-a5b8-372d097b4e58
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref BucketName
        LogFilePrefix: "access-logs/"

  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

Outputs:
  BucketName:
    Description: Name of the S3 bucket created
    Value: !Ref SecureS3Bucket

  LambdaRoleArn:
    Description: ARN of the Lambda IAM Role
    Value: !GetAtt LambdaIAMRole.Arn
